language: cpp
sudo: required
dist: trusty
compiler:
    - gcc
install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq mpi-default-bin mpi-default-dev cmake
    - sudo apt-get install -y -qq libboost1.56-all-dev
script: 
    - cd build/release && cmake ../../ -DCMAKE_BUILD_TYPE=Release && make && cd ../../test && ./run_tests.sh

notifications:
    email:
        recipients: 
            - fzenke@stanford.edu
        on_success: change
        on_failure: always
